spring:
  application:
    name: chat-service
  cloud:
    config:
      enabled: false
  config:
    import:
      - optional:file:./chat/.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create # Entity 기반으로 테이블을 자동 생성 여부 결정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # mongoDB
  data:
    mongodb:
      uri: ${MONGO_URL}

server:
  port: ${CHAT_SEVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${EUREKA_SEVER_PORT}/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:${ZIPKIN_SEVER_PORT}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0