spring:
  application:
    name: chat-service
  cloud:
    config:
      enabled: false
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Entity 기반으로 테이블을 자동 생성 여부 결정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # mongoDB
  data:
    mongodb:
      uri: ${MONGO_URL}

  # redis
    redis:
      host: localhost
      port: ${REDIS_SERVER_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

server:
  port: ${CHAT_SEVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${EUREKA_SEVER_PORT}/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:${ZIPKIN_SEVER_PORT}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.team15gijo.chat.presentation.handler: DEBUG

feign:
  client:
    config:
      user-service: # user-service에 대한 설정
        connectTimeout: 5000 # 연결 타임아웃 (ms)
        readTimeout: 5000 # 읽기 타임아웃 (ms)
        retryer: feign.Retryer.Default # 재시도 정책