name: filebeat

filebeat.inputs:
  - type: log
    id: error-log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/error*.log  # error.log 및 날짜별 error 로그만 수집
    fields:
      index_name: "error-log"
  - type: log
    id: api-log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/api*.log  # error.log 및 날짜별 error 로그만 수집
    fields:
      index_name: "api-log"

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.logstash:
  hosts: [ "logstash:5044" ]


http:
  enabled: true
  host: 0.0.0.0
