global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loko'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:19100'
          - 'host.docker.internal:19101'
          - 'host.docker.internal:19102'
          - 'host.docker.internal:19097'