spring:
  application:
    name: gateway-service
  config:
    import: optional:file:./gateway/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/api/v1/users/**
          filters:
          - StripPrefix=0


server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ?? URL

jwt:
  secret:
    key: ${JWT_SECRET_KEY}