server:
  port: 19095

spring:
  cloud:
    config:
      enabled: false
  config:
    import:
      - optional:file:./ai/.env.prod[.properties]
  application:
    name: ai-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
gemini:
  api-url: ${GEMINI_API_URL}
  api-key: ${GEMINI_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:19090/eureka/
    register-with-eureka: true   # 클라이언트가 Eureka에 자기 자신을 등록
    fetch-registry: true         # 다른 서비스 정보(Eureka 레지스트리)도 가져옴
  instance:
    prefer-ip-address: false
    hostname: ai-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

