version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: monogo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fifteen
      MONGO_INITDB_ROOT_PASSWORD: 15gijo
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongodb-data: